import type { ComponentType, SVGProps } from "react";
import {
  Activity,
  ArrowRight,
  BadgeCheck,
  BarChart3,
  Bot,
  CheckCircle,
  Clock,
  Code,
  Cpu,
  Database,
  EyeOff,
  FileLock,
  Fingerprint,
  Gamepad2,
  Gift,
  GitBranch,
  Hash,
  Lock,
  Mic,
  Network,
  Palette,
  Radio,
  ScanFace,
  ScanLine,
  Server,
  ServerOff,
  Shield,
  Smartphone,
  Trash2,
  Users,
  Vote,
  Waves,
} from "lucide-react";
import { SolanaIcon } from "./solana-icon";

type IconComponent = ComponentType<SVGProps<SVGSVGElement> & { strokeWidth?: number }>;

const iconMap: Record<string, IconComponent> = {
  pulse: Waves,
  proof: Fingerprint,
  anchor: BadgeCheck,
  airdrop: Gift,
  vote: Vote,
  bot: Bot,
  code: Code,
  github: GitBranch,
  shield: ScanFace,
  chart: BarChart3,
  globe: Network,
  zap: Radio,
  clock: Clock,
  users: Users,
  cpu: Cpu,
  "arrow-right": ArrowRight,
  mic: Mic,
  activity: Activity,
  hash: Hash,
  lock: Lock,
  scan: ScanLine,
  "check-circle": CheckCircle,
  gamepad: Gamepad2,
  palette: Palette,
  "eye-off": EyeOff,
  server: Server,
  "server-off": ServerOff,
  trash: Trash2,
  smartphone: Smartphone,
  database: Database,
  "file-lock": FileLock,
  solana: SolanaIcon,
};

export function getIcon(key: string): IconComponent {
  return iconMap[key] ?? Shield;
}
